# Generated by Django 5.1.4 on 2025-04-08 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0002_remove_teacherstudent_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomposition',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='studentcomposition',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='instruments',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='instrument',
        ),
        migrations.AddField(
            model_name='students',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='teachers',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Compositions',
        ),
        migrations.DeleteModel(
            name='StudentComposition',
        ),
    ]
