# Generated by Django 5.1.4 on 2025-04-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options_alter_subject_options_and_more'),
        ('users', '0003_remove_studentcomposition_comp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompletionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'verbose_name': 'Время прохождения урока',
                'verbose_name_plural': 'Время прохождения уроков',
            },
        ),
    ]
