# Generated by Django 5.1.4 on 2025-04-10 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lessoncompletiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade_of_school',
            field=models.IntegerField(null=True, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фио'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фио'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')]),
        ),
    ]
