# Generated by Django 5.1.4 on 2025-04-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_test'),
        ('users', '0005_alter_students_email_alter_students_grade_of_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('scores', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.test')),
            ],
        ),
    ]
