# Generated by Django 5.1.4 on 2025-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_testresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
