# Generated by Django 5.1.4 on 2025-04-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_testresult_options_alter_testresult_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='email',
        ),
    ]
