# Generated by Django 5.1.4 on 2025-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_test_topic'),
        ('users', '0008_remove_students_email_remove_teachers_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='completion_time',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('student', 'test')},
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempt_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testresult',
            name='incorrect_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='scores',
        ),
    ]
