# Generated by Django 5.1.4 on 2025-05-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonCompletionTime',
        ),
    ]
