# Generated by Django 5.1.4 on 2025-04-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='lessonvideo',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
