# Generated by Django 5.1.4 on 2025-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='educationplan',
            name='program_file',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
