# Generated by Django 5.1.4 on 2025-05-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_test_options_alter_educationplan_program_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
