# Generated by Django 5.1.4 on 2025-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_lesson_options_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
