# Generated by Django 5.1.4 on 2025-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_lesson_slug_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
