# Generated by Django 5.1.4 on 2025-05-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_test_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='LessonImage',
        ),
        migrations.DeleteModel(
            name='LessonVideo',
        ),
    ]
