# Generated by Django 5.1.4 on 2025-05-15 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_lessonvideo_lesson_delete_lessonimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarTrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('recognition', 'Распознавание'), ('performance', 'Воспроизведение')], max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('reference_notes', models.JSONField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarTrainingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('played_notes', models.JSONField(blank=True, null=True)),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.eartrainingtask')),
            ],
        ),
        migrations.CreateModel(
            name='EarTrainingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='eartrainingtask',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.eartrainingtest'),
        ),
    ]
