# Generated by Django 5.1.4 on 2025-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_eartrainingtask_eartrainingattempt_eartrainingtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eartrainingtask',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы за задание'),
        ),
    ]
