# Generated by Django 5.1.4 on 2025-06-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_eartrainingtask_points'),
        ('users', '0010_delete_lessoncompletiontime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eartrainingattempt',
            options={'ordering': ['id'], 'verbose_name': 'Попытка ученика по заданию', 'verbose_name_plural': 'Попытки ученика по заданию'},
        ),
        migrations.AlterModelOptions(
            name='eartrainingtask',
            options={'ordering': ['test__id', 'id'], 'verbose_name': 'Тест слухового диктанта', 'verbose_name_plural': 'Тесты слуховых диктантов'},
        ),
        migrations.AlterModelOptions(
            name='eartrainingtest',
            options={'ordering': ['id'], 'verbose_name': 'Контрольная слухового диктанта', 'verbose_name_plural': 'Контрольные слуховых диктантов'},
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.teachers', verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='school.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.students', verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
    ]
